### ISSUE TITLE
Runtime error using this code NestedDepth

### ISSUE THREAD

**Issue by AbhiAndroidManiac** [salvois/codejam#1]
Your code on running in the practice editor of the codejam giving runtime error.
Any comment on that.

**Comment by salvois** [comment]
Hello @AbhiAndroidManiac,
sorry for the late reply.
I just compared my version of Nesting Depth from Code Jam qualification round 2020 on Github against the very code submitted during the contest and judged as correct. It is the same besides the following differences, which are expected:

- package declaration removed
- class name renamed to Solution
- DEBUG constant set to false

Moreover, I have just copy-pasted the code on Github on the Code Jam practice platform, applied the above modification, and had the solution judged as correct.
Perhaps you missed some of those steps?
Thanks,
   Salvo
